apiVersion: batch/v1
kind: Job
metadata:
  name: vault-plugin-secrets-test
  namespace: REPLACE_NAMESPACE
spec:
  template:
    metadata:
      labels:
        app: vault-plugin-secrets-test-REPLACE_IMAGETAG
    spec:
      restartPolicy: OnFailure
      containers:
      - name: vault-plugin-secrets-test
        image: REPLACE_DOCKER_REPO:REPLACE_IMAGETAG
        imagePullPolicy: Always
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
        ports:
        - containerPort: 8200
          name: port8200
        volumeMounts:
        - mountPath: "/data/"
          name: data
        env:
        - name: VAULT_ADDR
          value: "http://127.0.0.1:8200"
        - name: VAULT_API_ADDR
          value: "http://127.0.0.1:8200"
        - name: UNSEAL
          value: "true"
      volumes:
      - persistentVolumeClaim:
          claimName: vault-plugin-secrets-test
        name: data
  backoffLimit: 6
