---
apiVersion: v1
kind: Service
metadata:
  name: key-vault-svc-int
  namespace: REPLACE_NAMESPACE
  annotations:
    "service.beta.kubernetes.io/aws-load-balancer-internal": "0.0.0.0/0"
  labels:
    app: key-vault
spec:
  type: LoadBalancer
  ports:
    - port: 8200
      protocol: TCP
      targetPort: 8200
      name: port8200
  selector:
    app: key-vault
---
apiVersion: v1
kind: Service
metadata:
  name: key-vault-svc
  namespace: REPLACE_NAMESPACE
  labels:
    app: key-vault
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8200
      name: port8200
  selector:
    app: key-vault
---
apiVersion: REPLACE_API_VERSION 
kind: Deployment
metadata:
  labels:
    app: key-vault
  name: key-vault
  namespace: REPLACE_NAMESPACE
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: key-vault
  template:
    metadata:
      labels:
        app: key-vault
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution: 
            nodeSelectorTerms:
            - matchExpressions:
              - key: node.kubernetes.io/instance-type
                operator: In
                values:
                - r4.large
      containers:
      - name: key-vault
        image: REPLACE_DOCKER_REPO:REPLACE_IMAGETAG 
        imagePullPolicy: Always
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
        ports:
        - containerPort: 8200
          name: port8200
        volumeMounts:
        - mountPath: "/data/"
          name: data
        env:
        - name: VAULT_ADDR
          value: "http://vault.stage.bloxinfra.com:8200"

        - name: VAULT_API_ADDR
          value: "http://vault.stage.bloxinfra.com:8200"

        - name: UNSEAL
          value: "true"

        - name: LOG_FORMAT
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: log_format

        - name: LOG_LEVELS
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: log_levels

        - name: LOG_DNS
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: log_dsn
              
        - name: LAUNCHTESTNET_GENESIS_TIME:
          value: "2020-09-29 12:00:13 UTC"
          
        - name: TESTNET_GENESIS_TIME
          value: "2020-08-04 13:00:08 UTC"
              

      volumes:
      - persistentVolumeClaim:
          claimName: key-vault
        name: data
