stages:
  - lint
  - test
  - build
  - deploy

variables:

  #GLOBAL
  IMAGE_NAME: vault-plugin-secrets
  REPLICAS: "1"

  #STAGE
  ACCOUNT_ID_INFRA_STAGE: 121827225315
  AWS_REGION_INFRA_STAGE: "us-west-2"
  DOCKER_REPO_INFRA_STAGE: $ACCOUNT_ID_INFRA_STAGE.dkr.ecr.$AWS_REGION_INFRA_STAGE.amazonaws.com/$IMAGE_NAME
  APP_REPLICAS_INFRA_STAGE: "1"
  ECRLOGIN_INFRA_STAGE: "aws ecr get-login --registry-ids $ACCOUNT_ID_INFRA_STAGE --region $AWS_REGION_INFRA_STAGE --no-include-email"
  TESTS_YAML: "jobs/valut-plugin-secrets-tests-job.yml"


#blox-infra-stage
Run linter:
  stage: lint
  image: golang:1.14-stretch
  tags:
    - blox-infra-stage
  script:
    - go get -u golang.org/x/lint/golint
    - go get -u golang.org/x/tools/cmd/goimports
    - ./scripts/lint.sh .

Run tests of the application:
  stage: test
  tags:
    - blox-infra-stage
  variables:
    DOCKER_REPO_PATH=/go/src/github.com/bloxapp/vault-plugin-secrets-eth2.0
  before_script:
    - apk update
  script:
    - export K8S_API_VERSION=$INFRA_STAGE_K8_API_VERSION
    - docker build -t $IMAGE_NAME:$CI_BUILD_REF -f Dockerfile .
    - .k8/scripts/deploy-single-yaml.sh $IMAGE_NAME $CI_BUILD_REF validators $TESTS_YAML blox-infra-stage kubernetes-admin@blox-infra k8.stage.bloxinternal.com $K8S_API_VERSION
#    - docker run -i --privileged $IMAGE_NAME:$CI_BUILD_REF --test
    - docker run -v "$PWD:$DOCKER_REPO_PATH" -i golang:1.14-stretch /bin/bash -c "cd $DOCKER_REPO_PATH && go get -t && go test -cover -race -p 1 ./..."

Build stage Docker image:
  stage: build
  tags:
    - blox-infra-stage
  script:
    - docker build -t $IMAGE_NAME:$CI_BUILD_REF -f Dockerfile .
    - DOCKER_LOGIN_TO_INFRA_STAGE_REPO=`$ECRLOGIN_INFRA_STAGE`
    - docker tag $IMAGE_NAME:$CI_BUILD_REF $DOCKER_REPO_INFRA_STAGE:$CI_BUILD_REF
    - $DOCKER_LOGIN_TO_INFRA_STAGE_REPO && docker push $DOCKER_REPO_INFRA_STAGE:$CI_BUILD_REF
  only:
    - stage

Deploy to blox-infra-stage cluster:
  stage: deploy
  tags:
    - blox-infra-stage
  script:
    - apk add bash
    - export K8S_API_VERSION=$INFRA_STAGE_K8_API_VERSION
    - .k8/scripts/deploy-yamls-on-k8s.sh $DOCKER_REPO_INFRA_STAGE $CI_BUILD_REF validators $APP_REPLICAS_INFRA_STAGE blox-infra-stage kubernetes-admin@blox-infra k8.stage.bloxinternal.com $K8S_API_VERSION
  only:
    - stage
