version: '3.7'

services:
  vault:
    build:
      context: .
      dockerfile: Dockerfile
#    image: bloxstaking/key-vault:latest
    ports:
      - 8200:8200
    volumes:
      - ./data:/data
      - ./policies:/policies
    environment:
      VAULT_ADDR: "http://127.0.0.1:8200"
      VAULT_API_ADDR: "http://127.0.0.1:8200"
      VAULT_CLIENT_TIMEOUT: "30s"
      UNSEAL: "true"
      # This is needed only for development coz we can't see plugin logs.
      LOG_FORMAT: ${LOG_FORMAT}
      LOG_LEVELS: ${LOG_LEVELS}
      LOG_DSN: ${LOG_DSN}
      # Genesis times per network
      TESTNET_GENESIS_TIME: "2020-08-04 13:00:08 UTC"
      LAUNCHTESTNET_GENESIS_TIME: "2020-09-29 12:00:13 UTC"
    cap_add:
      - IPC_LOCK
    restart: unless-stopped

  vault-image:
    image: bloxstaking/key-vault:v0.1.6
    ports:
      - 8200:8200
    volumes:
      - ./data:/data
      - ./policies:/policies
    environment:
      VAULT_ADDR: "http://127.0.0.1:8200"
      VAULT_API_ADDR: "http://127.0.0.1:8200"
      VAULT_CLIENT_TIMEOUT: "30s"
      UNSEAL: "true"
      # Genesis times per network
      TESTNET_GENESIS_TIME: "2020-08-04 13:00:08 UTC"
      LAUNCHTESTNET_GENESIS_TIME: "2020-09-29 12:00:13 UTC"
    cap_add:
      - IPC_LOCK
    restart: unless-stopped
