---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: vault-plugin-secrets
  namespace: validators
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: gp2
